# Generated by Django 4.2.9 on 2026-10-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='冻结时间'),
        ),
        migrations.AddField(
            model_name='goods',
            name='frozen_reason',
            field=models.TextField(blank=True, verbose_name='冻结原因'),
        ),
        migrations.AddField(
            model_name='goods',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='是否冻结'),
        ),
        migrations.AddField(
            model_name='goods',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='占用数量'),
        ),
    ]
