# Generated by Django 4.2.9 on 2026-10-03 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='需求数量')),
                ('required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '可替代项分组',
                'verbose_name_plural': '可替代项分组',
                'db_table': 'wh_kit_item_group',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='申请单号')),
                ('receiver', models.CharField(max_length=100, verbose_name='领用人')),
                ('receiver_dept', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('issued', '已发放'), ('partial_returned', '部分退回'), ('returned', '全部退回'), ('cancelled', '已撤回')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kit_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '领用申请',
                'verbose_name_plural': '领用申请',
                'db_table': 'wh_kit_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='领用包名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kits', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '领用包定义',
                'verbose_name_plural': '领用包定义',
                'db_table': 'wh_kit_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='frozen_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='冻结数量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='occupied_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='领用占用数量'),
        ),
        migrations.CreateModel(
            name='StockFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('freeze', '冻结'), ('unfreeze', '解冻')], max_length=20, verbose_name='类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('reason', models.TextField(verbose_name='冻结/解冻原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_records', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_freeze_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '物资冻结记录',
                'verbose_name_plural': '物资冻结记录',
                'db_table': 'wh_stock_freeze',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已生效'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('change_remark', models.TextField(blank=True, verbose_name='升级说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kit_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='warehouse.kittemplate', verbose_name='领用包')),
            ],
            options={
                'verbose_name': '领用包版本',
                'verbose_name_plural': '领用包版本',
                'db_table': 'wh_kit_version',
                'ordering': ['template', '-version_no'],
                'unique_together': {('template', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='KitRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='分组名称')),
                ('required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('is_alternative', models.BooleanField(default=False, verbose_name='是否可替代项')),
                ('selection_reason', models.TextField(blank=True, verbose_name='选择依据')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请数量')),
                ('occupied_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='占用数量')),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已发放数量')),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已退回数量')),
                ('status', models.CharField(choices=[('occupied', '已占用'), ('released', '已释放'), ('issued', '已发放'), ('partial_returned', '部分退回'), ('returned', '已退回')], default='occupied', max_length=20, verbose_name='状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_request_lines', to='warehouse.goods', verbose_name='货物')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_lines', to='warehouse.kititemgroup', verbose_name='替代分组')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.kitrequest', verbose_name='领用申请')),
            ],
            options={
                'verbose_name': '领用申请明细',
                'verbose_name_plural': '领用申请明细',
                'db_table': 'wh_kit_request_line',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='kitrequest',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='warehouse.kittemplate', verbose_name='领用包'),
        ),
        migrations.AddField(
            model_name='kitrequest',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='warehouse.kitversion', verbose_name='展开版本'),
        ),
        migrations.AddField(
            model_name='kititemgroup',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='warehouse.kitversion', verbose_name='包版本'),
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='需求数量')),
                ('required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='warehouse.goods', verbose_name='货物')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='warehouse.kititemgroup', verbose_name='所属替代分组')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.kitversion', verbose_name='包版本')),
            ],
            options={
                'verbose_name': '领用包明细',
                'verbose_name_plural': '领用包明细',
                'db_table': 'wh_kit_item',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='kititemgroup',
            unique_together={('version', 'name')},
        ),
    ]
