# Generated by Django 4.2.9 on 2026-10-03 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0002_goods_frozen_at_goods_frozen_reason_goods_is_frozen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='包名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='包编码')),
                ('description', models.TextField(blank=True, verbose_name='用途说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kits', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '领用包',
                'verbose_name_plural': '领用包',
                'db_table': 'kit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100, verbose_name='领用人')),
                ('receiver_dept', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('status', models.CharField(choices=[('shortage', '缺货待补'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('issued', '已发放'), ('partially_returned', '部分退回'), ('returned', '已退回'), ('cancelled', '已取消')], default='pending', max_length=30, verbose_name='状态')),
                ('shortage_detail', models.JSONField(blank=True, default=list, verbose_name='缺货明细')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='发放时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kit_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '领用申请',
                'verbose_name_plural': '领用申请',
                'db_table': 'kit_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('retired', '已停用')], default='draft', max_length=20, verbose_name='状态')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='版本说明')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kit_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='kits.kit', verbose_name='所属领用包')),
            ],
            options={
                'verbose_name': '领用包版本',
                'verbose_name_plural': '领用包版本',
                'db_table': 'kit_version',
                'ordering': ['-version_no'],
                'unique_together': {('kit', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', '主机'), ('accessory', '配件'), ('media', '封存介质')], default='accessory', max_length=20, verbose_name='组合角色')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='每套数量')),
                ('required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='warehouse.goods', verbose_name='主选货物')),
                ('substitutes', models.ManyToManyField(blank=True, related_name='substitute_in_kit_items', to='warehouse.goods', verbose_name='可替代货物')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kits.kitversion', verbose_name='所属版本')),
            ],
            options={
                'verbose_name': '领用包物资项',
                'verbose_name_plural': '领用包物资项',
                'db_table': 'kit_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KitApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', '主机'), ('accessory', '配件'), ('media', '封存介质')], max_length=20, verbose_name='组合角色')),
                ('required', models.BooleanField(verbose_name='是否必需')),
                ('is_substitute', models.BooleanField(default=False, verbose_name='是否替代物资')),
                ('substitute_reason', models.CharField(blank=True, max_length=200, verbose_name='替代选择依据')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请数量')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='占用数量')),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='发放数量')),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已退数量')),
                ('status', models.CharField(choices=[('reserved', '已占用'), ('issued', '已发放'), ('partially_returned', '部分退回'), ('returned', '已退回'), ('released', '已释放')], default='reserved', max_length=30, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kits.kitapplication', verbose_name='所属申请')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_application_items', to='warehouse.goods', verbose_name='实际占用货物')),
                ('kit_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_items', to='kits.kititem', verbose_name='来源定义项')),
            ],
            options={
                'verbose_name': '领用申请明细',
                'verbose_name_plural': '领用申请明细',
                'db_table': 'kit_application_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='kitapplication',
            name='kit_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='kits.kitversion', verbose_name='锁定的包版本'),
        ),
    ]
